Home work 2
Terramora/Django-Framework-Basics pull request #2
Opened 2021-06-27 16:19 UTC by Terramora

2021-06-27 20:32 UTC, Vokler requested changes

2021-06-27 20:32 UTC, Vokler commented on products/fixtures/products.json
> +  "title": "Products",
В этом json файле нужно хранить только информацию о продуктах
title лучше указывать в самом контроллере

2021-06-27 20:32 UTC, Vokler commented on products/views.py
> +    with open('C:\\Users\\Terramora.CNV\\Documents\\GitHub\\Django\\geekshop\\products\\fixtures\\products.json', 'r',
попробуйте так
`products = BASE_DIR / 'products/fixtures/products.json'`

2021-06-28 05:24 UTC, Terramora commented
Запушил изменения тайтла + абсолютного пути.

Импортировать BASE_DIR я пробовал, но это не сработало. Видимо где-то опечатывался.

2021-06-28 06:42 UTC, Vokler approved these changes

2021-06-28 06:42 UTC, merged